spring:
  application:
    name: user-backend-api
  jackson:
    time-zone: UTC
  cloud:
    vault:
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      scheme: ${VAULT_SCHEME}
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: user-backend-api
  datasource:
    url: ${DB_URL}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  defer-datasource-initialization: true
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  server:
    port: 8080
    address: 0.0.0.0
    forward-headers-strategy: framework
  profiles:
    active: local

jwt:
  secret-reset: ${jwt_secret_reset}
  secret-key: ${jwt_secret_key}
  expiration-time: 3600000

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}