name: Pull Request

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    # 🐘 DB de test pour Spring Boot
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: cesizen
          POSTGRES_PASSWORD: cesizen
          POSTGRES_DB: cesizen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U cesizen -d cesizen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      # 📥 Code
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ☕ Java 21
      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 🧪 Tests + build + coverage
      - name: Build + tests Maven
        run: mvn clean verify -e -X
        env:
          # BDD
          URL: jdbc:postgresql://localhost:5432/cesizen
          USERNAME_DB: cesizen
          PASSWORD_DB: cesizen
          jwt_secret_reset: "this-is-a-very-long-secure-key-at-least-32-characters-long!!"
          jwt_secret_key: "another-very-long-secure-key-at-least-32-characters-long!!"
          USERNAME_MAIL: test@example.com
          PASSWORD_MAIL: fake-password
          SPRING_PROFILE_ACTIVE: test

      # 📦 Sauvegarde les rapports
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      # 📊 SonarQube
      - name: Analyse SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=CESIZen--backend-api \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # 🐳 Build Docker image
      - name: Build Docker image
        run: |
          docker build -t cesizen-api:${{ github.sha }} .

      # 🧪 Test container API
      - name: Run API container
        run: |
          docker run -d \
            --network host \
            --name api \
            -e URL=jdbc:postgresql://localhost:5432/cesizen \
            -e USERNAME_DB=cesizen \
            -e PASSWORD_DB=cesizen \
            -e jwt_secret_key="this-is-a-very-long-secret-key-for-ci-123!" \
            -e jwt_secret_reset="another-very-long-secret-reset-key-ci-456!" \
            -e USERNAME_MAIL=test@example.com \
            -e PASSWORD_MAIL=fake-password \
            cesizen-api:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: docker rm -f api || true