name: Pull Request

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    # base de données test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U cesizen -d cesizen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # tests - build - coverage
      - name: Build + tests Maven
        run: mvn clean verify -e -X
        env:
          # base de données
          URL: ${{ secrets.URL }}
          USERNAME_DB: ${{ secrets.USERNAME_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
          jwt_secret_reset: ${{ secrets.JWT_SECRET_RESET }}
          jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
          USERNAME_MAIL: ${{ secrets.USERNAME_MAIL }}
          PASSWORD_MAIL: ${{ secrets.PASSWORD_MAIL }}
          SPRING_PROFILE_ACTIVE: test

      # sauvegarde les rapports
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      # 📊 SonarQube
      - name: Analyse SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=CESIZen--backend-api \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # 🐳 Build Docker image
      - name: Build Docker image
        run: |
          docker build -t cesizen-api:${{ github.sha }} .

      # 🔒 Scan Trivy image Docker
      - name: Scan Trivy de l'image Docker
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: cesizen-api:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: '1'
          ignore-unfixed: true

      # 🧪 Test container API
      - name: Run API container
        run: |
          docker run -d \
            --network host \
            --name api \
            -e URL=${{ secrets.URL }} \
            -e USERNAME_DB=${{ secrets.USERNAME_DB }} \
            -e PASSWORD_DB=${{ secrets.PASSWORD_DB }} \
            -e jwt_secret_key=${{ secrets.JWT_SECRET_KEY }} \
            -e jwt_secret_reset=${{ secrets.JWT_SECRET_RESET }} \
            -e USERNAME_MAIL=${{ secrets.USERNAME_MAIL }} \
            -e PASSWORD_MAIL=${{ secrets.PASSWORD_MAIL }} \
            cesizen-api:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: docker rm -f api || true