name: Pull Request

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      # Checkout (IMPORTANT pour Sonar)
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test variables CI
        run: |
          echo "DB URL = $SPRING_DATASOURCE_URL"
          echo "DB USER = $SPRING_DATASOURCE_USERNAME"

          if [ -z "$SPRING_DATASOURCE_URL" ]; then
            echo "❌ SPRING_DATASOURCE_URL VIDE"
            exit 1
          fi

          echo "✅ Variables OK"
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.URL_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.USERNAME_DB }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.PASSWORD_DB }}

      # Java 21
      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Build + tests + JaCoCo
      - name: Compiler et exécuter les tests Maven
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.URL_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.USERNAME_DB }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.PASSWORD_DB }}

      # SonarQube analysis
      - name: Analyse SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=CESIZen \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml